// UI string constants for localization support

export const strings = {
  // Navigation
  nav: {
    discovery: "Discovery",
    routing: "Routing",
    tools: "Tools",
    config: "Config",
    services: "Services",
    mappings: "Mappings",
    proxyRules: "Proxy Rules",
    capture: "Capture",
    requests: "Requests",
    mocks: "Mocks",
    sockets: "Sockets",
    environments: "Envs & Vars",
    settings: "Settings",
  },

  // Title bar
  titleBar: {
    appName: "Local Panel",
    collapseSidebar: "Collapse sidebar",
    expandSidebar: "Expand sidebar",
    switchEnvironment: "Switch environment",
    noEnvironment: "No Env",
    manageEnvironments: "Manage Environments…",
    environment: "Environment",
    noEnv: "No Environment",
    stopServer: "Stop server",
    startServer: "Start server",
    portInUse: "Port {port} in use",
    active: "Active :{port}",
    stopped: "Stopped :{port}",
    serverRunning: "Server running",
    switchWorkspace: "Switch workspace",
    createWorkspace: "Create Workspace",
    workspaces: "Workspaces",
  },

  // Common actions
  common: {
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    close: "Close",
    edit: "Edit",
    add: "Add",
    import: "↑ Import",
    export: "↓ Export",
    addRow: "Add Row",
    format: "Format",
    noHeaders: "No headers",
    noHeadersAddRow: "No headers — click Add Row",
    noHeadersCaptured: "No headers captured",
    noHeadersAddRowBelow: "No headers — click Add Row below",
    emptyBody: "empty body",
    noResults: "No results.",
    key: "Key",
    value: "Value",
  },

  // Server status
  server: {
    running: "Server running on port {port} — access via {hint}",
    notRunning: "Server not running",
    error: "{error}. Kill the process using that port or change the port above, then restart the server.",
    restarting: "Restarting…",
    restart: "Restart",
    sending: "Sending…",
    send: "▶ Send",
    saving: "Saving…",
    testing: "Testing…",
    test: "▶ Test",
  },

  // Mocks panel
  mocks: {
    title: "Mocks",
    noMocksYet: "No mocks yet.\nClick  +  in the tab bar to create one.",
    noMocksOpen: "No mocks open",
    noMocksOpenHint: "Click a mock in the tree, or press + to create a new one.",
    newMock: "New Mock",
    editMock: "Edit Mock",
    searchPlaceholder: "Search mocks…",
    mockCount: "{count} mock{s}",
    mockCountActive: "{count} mock{s} · {active} active",
    importTitle: "Import mocks from Postman Collection JSON",
    exportTitle: "Export mocks as Postman Collection JSON",
    imported: "Imported {n} mock{s} · {f} folder{fs}",
    exported: "Exported {n} mock{s}",
    importFailed: "Import failed",
    exportFailed: "Export failed",
    urlTreeView: "URL tree view",
    folderView: "Folder view",
    collapseSidebar: "Collapse sidebar",
    expandSidebar: "Expand sidebar",
    expandAll: "Expand All",
    collapseAll: "Collapse All",
    openInTab: "Open in Tab",
    enable: "Enable",
    disable: "Disable",
    enableAll: "Enable All",
    disableAll: "Disable All",
    deleteAll: "Delete All ({n})",
    newTab: "New mock",
    closeTab: "Close tab",
    drafts: "Drafts",
    helpText: "Create HTTP mock endpoints that return fixed responses. Mocks intercept matching requests through the proxy before they reach real servers. Use {{VAR}} in URL patterns, response headers, and body to substitute environment variables.",
    mocksNote: "Mocks take priority over proxy rules and passthrough",
    addResponseBody: "Add a response body to save",
    saveMock: "Save Mock",
    importFromCurl: "Import from cURL",
    importFromCurlHint: "— paste a bash curl command to auto-fill method, URL, headers and body",
    mockName: "Mock name (optional)",
    urlPatternPlaceholder: "http://example.localhost/endpoint",
    curlPlaceholder: "curl -X POST http://example.localhost/endpoint \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"key\": \"value\"}'",
  },

  // Requests panel
  requests: {
    title: "Requests",
    noRequestsYet: "No saved requests yet.\nClick  +  in the tab bar.",
    noRequestsOpen: "No requests open",
    noRequestsOpenHint: "Click a request in the tree, or press + to create a new one.",
    newRequest: "New Request",
    editRequest: "Edit Request",
    searchPlaceholder: "Search requests…",
    requestCount: "{count} request{s}",
    importTitle: "Import requests from Postman Collection JSON",
    exportTitle: "Export requests as Postman Collection JSON",
    imported: "Imported {n} request{s} · {f} folder{fs}",
    exported: "Exported {n} request{s}",
    importFailed: "Import failed",
    exportFailed: "Export failed",
    requestNamePlaceholder: "Request name (optional)",
    urlPlaceholder: "https://example.localhost/endpoint",
    importFromCurl: "Import from cURL",
    curlPlaceholder: "curl -X POST https://example.localhost/endpoint \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"key\": \"value\"}'",
    createMock: "⚡ Create Mock",
    createMockTitle: "Create a mock pre-filled with this request + response",
    hitSendPrompt: "Hit Send to see the response",
    helpText: "Save and replay HTTP requests. Use the URL tree or folder view in the sidebar to browse saved requests. Paste a cURL command to auto-fill fields. After sending, use 'Create Mock' to instantly stub the response. Use {{VAR}} tokens in URL, headers, and body with an active environment.",
    newTab: "New request",
    closeTab: "Close",
    drafts: "Drafts",
  },

  // Capture panel
  capture: {
    title: "Capture",
    helpText: "Capture live HTTP requests passing through the proxy. Click 'Mock' to create a mock pre-filled with the captured request/response. Click 'Open' to replay in the Requests panel. Pause to stop the live feed.",
    exportTitle: "Export captured requests as Postman collection",
    exported: "Exported {n} request{s}",
    exportFailed: "Export failed",
  },

  // Mappings panel
  mappings: {
    title: "Localhost Mappings",
    subtitle: "Map *.localhost domains to local services",
    noMappingsYet: "No mappings yet",
    noMappingsYetHint: "Map a .localhost subdomain to a local service port.",
    noMatchingMappings: "No matching mappings",
    noMatchingMappingsHint: "Try a different search term.",
    addMapping: "+ Add Mapping",
    editMapping: "Edit Mapping",
    addMappingTitle: "Add Mapping",
    searchPlaceholder: "Domain, target…",
    columnDomain: "Domain",
    columnTarget: "Target",
    columnLabel: "Label",
    columnOn: "On",
    helpText: "Create subdomain mappings like example.localhost → 127.0.0.1:3000. Browsers resolve *.localhost to 127.0.0.1 automatically (RFC 6761) — no hosts file edits needed. The server must be running on port 80 for bare hostnames to work.",
    subdomainLabel: "Subdomain",
    subdomainPlaceholder: "example or client.example",
    localHostSuffix: ".localhost",
    willCreate: "Will create:",
    targetLabel: "Target (ip:port)",
    targetPlaceholder: "127.0.0.1:3000",
    labelLabel: "Label (optional)",
    labelPlaceholder: "My App",
    subdomainRequired: "Subdomain is required",
    subdomainInvalid: "Each label must contain only letters, numbers, hyphens (no leading/trailing hyphens)",
    subdomainDuplicate: "{domain} is already mapped",
    targetInvalid: "Enter a valid host:port (e.g. 127.0.0.1:3000)",
    exportTitle: "Export mappings to JSON",
    importTitle: "Import mappings from JSON",
    exported: "Exported {n} mapping{s}",
    exportFailed: "Export failed",
    imported: "Imported {n} mapping{s}",
    importFailed: "Import failed",
  },

  // Settings panel
  settings: {
    title: "Settings",
    subtitle: "Server configuration and data management",
    helpText: "Configure the proxy server port, tray behavior, and export/import your mappings and rules. Mocks and requests are managed separately in their own panels.",
    serverPort: "Server Port",
    serverPortDesc: "Port the server listens on. Use {hint} in your browser.",
    minimizeToTray: "Minimize to Tray on Close",
    minimizeToTrayDesc: "Keep the app running in the system tray instead of quitting when the window is closed.",
    restartServer: "Restart Server",
    restartServerDesc: "Stop and restart the background proxy server on the configured port.",
    exportConfig: "Export All Data",
    exportConfigDesc: "Save all workspaces and their data to a JSON file.",
    importConfig: "Import All Data",
    importConfigDesc: "Restore all workspaces from a previously exported JSON file. Replaces everything.",
    exportBtn: "Export…",
    importBtn: "Import…",
    configImported: "Config imported.",
    port80Hint: "Port 80:",
    port80Example: "example.localhost",
    port80Desc: "— browsers resolve {domain} to 127.0.0.1 automatically (RFC 6761).",
    otherPortHint: "Other port:",
    otherPortDesc: "Use {domain} in the browser. No proxy setup needed.",
    proxyHint: "System/browser proxy:",
    proxyDesc: "Optionally set {addr} as your HTTP proxy. Proxy rules then apply to all HTTP traffic. HTTPS is a transparent TCP tunnel — not inspected.",
    sectionServer: "Server",
    sectionTls: "TLS Interception",
    sectionConfig: "Configuration",
    sectionAbout: "About",
    tlsEnabled: "Intercept HTTPS",
    tlsEnabledDesc: "When enabled, HTTPS requests are decrypted so mocks and proxy rules can match them. Requires a trusted CA certificate configured below.",
    tlsCaCert: "CA Certificate",
    tlsCaCertDesc: "PEM-encoded CA certificate used to sign per-host certificates.",
    tlsCaKey: "CA Private Key",
    tlsCaKeyDesc: "Private key for the CA certificate.",
    tlsImport: "Import…",
    tlsRemove: "Remove",
    tlsNotConfigured: "Not configured",
    tlsInstallHint: "Install the CA certificate in your browser or OS trust store to avoid HTTPS warnings.",
    tlsGenerate: "Generate with mkcert",
    tlsGenerating: "Generating…",
    tlsInstallCA: "Install in System",
    tlsInstalling: "Installing…",
    tlsInstallSuccess: "Installed",
    tlsInstallFailed: "Install failed",
    tlsExportCert: "Export Cert…",
    tlsManualInstall: "Manual install required — run in a terminal:",
    tlsGenerateHint: "Generate a new local CA cert using mkcert (10-year validity, stored in app data). Then install it so browsers trust your local HTTPS.",
    darkMode: "Theme",
    darkModeDesc: "Choose a colour theme for the application",
    version: "Version",
    author: "Author",
    authorName: "Harshal Kudale",
    github: "GitHub",
    githubUrl: "https://github.com/HarshalKudale",
    githubDisplay: "github.com/HarshalKudale",
    license: "License",
    licenseName: "MIT License",
    appDesc: "Local development proxy & mock server",
  },

  // Services panel
  services: {
    title: "Services",
    helpText: "Discovers processes listening on localhost ports. Click 'Map →' next to any service to quickly create a localhost mapping for it. Hit Refresh to re-scan for new services.",
  },

  // Proxy rules panel
  proxyRules: {
    title: "Proxy Rules",
    helpText: "Proxy rules apply when Local Panel is configured as your system or browser HTTP proxy. Each rule matches a URL pattern and forwards matching requests to a mapped local service or external host. Rules are evaluated top-to-bottom — first match wins. Use request/response scripts to manipulate traffic.",
    exportTitle: "Export proxy rules to JSON",
    importTitle: "Import proxy rules from JSON",
    exported: "Exported {n} rule{s}",
    exportFailed: "Export failed",
    imported: "Imported {n} rule{s}",
    importFailed: "Import failed",
    newRule: "New Rule",
    newTab: "New rule",
    closeTab: "Close tab",
    drafts: "Drafts",
    noRulesOpen: "No rules open",
    searchPlaceholder: "Search rules…",
    collapseSidebar: "Collapse sidebar",
    expandSidebar: "Expand sidebar",
    saveRule: "Save Rule",
    ruleNamePlaceholder: "Rule name (optional)",
    targetMapping: "Mapped Service",
    targetExternal: "External Host",
    requestScript: "Request Script",
    responseScript: "Response Script",
    regexToggle: "Regex",
    exactToggle: "Exact",
    requestScriptPlaceholder: "// Runs before request is forwarded\n// lp.request.headers — mutable object\n// lp.request.body    — mutable string",
    responseScriptPlaceholder: "// Runs before response is returned\n// lp.response.headers — mutable object\n// lp.response.body    — mutable string",
  },

  // Environments panel
  environments: {
    title: "Environments",
    helpText: "Environments hold named variable sets. Switch the active environment from the title bar dropdown. Use {{VAR_NAME}} syntax anywhere in request/mock URLs, headers, body, or response body — values are substituted at send/match time. Variables not found in the active env are left as-is.",
    exportTitle: "Export environments to JSON",
    importTitle: "Import environments from JSON",
    exported: "Exported {n} environment{s}",
    exportFailed: "Export failed",
    imported: "Imported {n} environment{s}",
    importFailed: "Import failed",
  },

  // Sockets panel
  sockets: {
    helpText: "Open persistent WebSocket connections to local or remote servers. Save connections with URLs and headers for quick access. OutputStream shows sent messages; InputStream shows received messages. Use {{VAR}} tokens in URL and message body with an active environment. Max 5 live connections at any time.",
  },

  // Editor sections
  editor: {
    request: "Request",
    response: "Response",
    headers: "Headers",
    body: "Body",
    preScript: "Pre Script",
    postScript: "Post Script",
    inputstream: "InputStream",
    outputstream: "OutputStream",
    readOnly: "read-only",
    status: "Status",
    replayRequest: "Replay Request",
    back: "← Back",
    scriptPlaceholder: "// JavaScript — runs before the request is sent\n// Available: lp.request.url, lp.request.headers, lp.request.body\n//            lp.environment.get/set/unset\n//            await lp.sendRequest(requestId)  → { status, headers, body }",
    postScriptPlaceholder: "// JavaScript — runs after the response is received\n// Available: lp.response.status, lp.response.headers, lp.response.body, lp.response.json()\n//            lp.environment.get/set/unset\n//            await lp.sendRequest(requestId)  → { status, headers, body }",
    scriptError: "Script error",
  },

  // Workspace panel
  workspace: {
    title: "Workspace",
    subtitle: "Configure workspace settings and remote sync",
    helpText: "Manage workspace name and connect to a remote Git repository for syncing across machines. Connecting pushes local data to an empty remote, or clones an existing remote into an empty workspace.",
    sectionDetails: "Details",
    sectionSync: "Remote Sync",
    sectionData: "Data",
    sectionDanger: "Danger Zone",
    workspaceName: "Workspace Name",
    workspaceCreated: "Created",
    remoteUrl: "Remote URL",
    remoteUrlDesc: "Git repository URL. Cannot be changed once connected.",
    remoteUrlPlaceholder: "https://github.com/you/workspace-data.git",
    branch: "Branch",
    branchPlaceholder: "main",
    autoSync: "Auto-sync",
    autoSyncDesc: "Automatically push after changes and pull every 30 seconds.",
    connectBtn: "Connect",
    connectingBtn: "Connecting…",
    disconnectBtn: "Disconnect",
    pushBtn: "Push",
    pullBtn: "Pull",
    pushingBtn: "Pushing…",
    pullingBtn: "Pulling…",
    lastPushed: "Last pushed",
    lastPulled: "Last pulled",
    never: "never",
    statusIdle: "Synced",
    statusPushing: "Pushing…",
    statusPulling: "Pulling…",
    statusCloning: "Connecting…",
    statusError: "Error",
    exportBtn: "Export Workspace…",
    exportDesc: "Save this workspace's data to a JSON file.",
    importBtn: "Import Into Workspace…",
    importDesc: "Replace this workspace's data from a previously exported JSON file.",
    deleteBtn: "Delete Workspace",
    deleteDesc: "Permanently delete this workspace and all its data.",
    deleteConfirm: "This will permanently delete \"{name}\" and all its data. Are you sure?",
    deleteConfirmBtn: "Delete",
    connectWarningNonEmpty: "Your local data will be pushed to the remote. The remote must be empty.",
    connectWarningEmpty: "The remote repository will be cloned into this workspace. Continue?",
    confirmConnect: "Connect",
    cancelConnect: "Cancel",
    syncError: "Sync error",
    disconnectWarning: "Disconnect from remote? Local data is preserved.",
    disconnectConfirm: "Disconnect",
    imported: "Workspace imported",
    exported: "Workspace exported",
    importFailed: "Import failed",
    exportFailed: "Export failed",
  },

  // Applications panel
  applications: {
    title: "Applications",
    subtitle: "Run configurations for your workspace",
    helpText: "Configure and run application processes. Supports Node.js, Python, Java, .NET, Go, Docker, Maven, Gradle, Spring Boot, and shell scripts.",
    addApplication: "Add Application",
    updateApplication: "Update Application",
    noTitle: "No applications configured",
    noDesc: "Add run configurations to start, stop, and debug your applications from here.",
    labelName: "Name",
    labelType: "Type",
    labelWorkingDirectory: "Working Directory",
    labelCommand: "Command",
    labelScriptPath: "Script Path",
    labelScriptName: "Script Name",
    labelPackageManager: "Package Manager",
    labelModule: "Module (-m)",
    labelMainClass: "Main Class",
    labelJarPath: "JAR Path (optional)",
    labelClasspath: "Classpath",
    labelImage: "Image",
    labelPorts: "Ports (comma-separated)",
    labelComposeFile: "Compose File",
    labelArguments: "Arguments",
    labelPreRunCommand: "Pre-Run Command",
    labelDebugPort: "Debug Port",
    noOutputYet: "No output yet",
    debugListeningOn: "Debugger listening on port",
    statusRunning: "Running",
    statusDebugging: "Debugging",
    statusStarting: "Starting\u2026",
    statusStopping: "Stopping\u2026",
    statusError: "Error",
    statusExited: "Exited",
    statusIdle: "Idle",
    actionRun: "Run",
    actionDebug: "Debug",
    actionStop: "Stop",
    actionRestart: "Restart",
    logsTitle: "Output",
    logsClear: "Clear",
    logsScrollBottom: "Scroll to bottom",
  },

  // Import/export
  io: {
    cancelled: "Cancelled",
    importFailed: "Import failed",
    exportFailed: "Export failed",
  },
} as const;
