// UI string constants for localization support

export const strings = {
  // Navigation
  nav: {
    discovery: "Discovery",
    routing: "Routing",
    tools: "Tools",
    config: "Config",
    services: "Services",
    mappings: "Mappings",
    proxyRules: "Proxy Rules",
    capture: "Capture",
    requests: "Requests",
    mocks: "Mocks",
    sockets: "Sockets",
    environments: "Envs & Vars",
    settings: "Settings",
  },

  // Title bar
  titleBar: {
    appName: "Local Panel",
    collapseSidebar: "Collapse sidebar",
    expandSidebar: "Expand sidebar",
    switchEnvironment: "Switch environment",
    noEnvironment: "No Env",
    manageEnvironments: "Manage Environments…",
    environment: "Environment",
    noEnv: "No Environment",
    stopServer: "Stop server",
    startServer: "Start server",
    portInUse: "Port {port} in use",
    active: "Active :{port}",
    stopped: "Stopped :{port}",
    serverRunning: "Server running",
    switchWorkspace: "Switch workspace",
    createWorkspace: "Create Workspace",
    workspaces: "Workspaces",
  },

  // Common actions
  common: {
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    close: "Close",
    edit: "Edit",
    add: "Add",
    import: "Import",
    export: "Export",
    addRow: "Add Row",
    format: "Format",
    noHeaders: "No headers",
    noHeadersAddRow: "No headers — click Add Row",
    noHeadersCaptured: "No headers captured",
    noHeadersAddRowBelow: "No headers — click Add Row below",
    emptyBody: "empty body",
    noResults: "No results.",
    key: "Key",
    value: "Value",
  },

  // Server status
  server: {
    running: "Server running on port {port} — access via {hint}",
    notRunning: "Server not running",
    error: "{error}. Kill the process using that port or change the port above, then restart the server.",
    restarting: "Restarting…",
    restart: "Restart",
    sending: "Sending…",
    send: "Send",
    saving: "Saving…",
    testing: "Testing…",
    test: "Test",
  },

  // Mocks panel
  mocks: {
    title: "Mocks",
    noMocksYet: "No mocks yet.\nClick  +  in the tab bar to create one.",
    noMocksOpen: "No mocks open",
    noMocksOpenHint: "Click a mock in the tree, or press + to create a new one.",
    newMock: "New Mock",
    editMock: "Edit Mock",
    searchPlaceholder: "Search mocks…",
    mockCount: "{count} mock{s}",
    mockCountActive: "{count} mock{s} · {active} active",
    importTitle: "Import mocks from Postman Collection JSON",
    exportTitle: "Export mocks as Postman Collection JSON",
    imported: "Imported {n} mock{s} · {f} folder{fs}",
    exported: "Exported {n} mock{s}",
    importFailed: "Import failed",
    exportFailed: "Export failed",
    urlTreeView: "URL tree view",
    folderView: "Folder view",
    collapseSidebar: "Collapse sidebar",
    expandSidebar: "Expand sidebar",
    expandAll: "Expand All",
    collapseAll: "Collapse All",
    openInTab: "Open in Tab",
    enable: "Enable",
    disable: "Disable",
    enableAll: "Enable All",
    disableAll: "Disable All",
    deleteAll: "Delete All ({n})",
    newTab: "New mock",
    closeTab: "Close tab",
    drafts: "Drafts",
    helpText: "Create HTTP mock endpoints that return fixed responses. Mocks intercept matching requests through the proxy before they reach real servers. Use {{VAR}} in URL patterns, response headers, and body to substitute environment variables.",
    mocksNote: "Mocks take priority over proxy rules and passthrough",
    addResponseBody: "Add a response body to save",
    saveMock: "Save Mock",
    importFromCurl: "Import from cURL",
    importFromCurlHint: "— paste a bash curl command to auto-fill method, URL, headers and body",
    mockName: "Mock name (optional)",
    urlPatternPlaceholder: "http://example.localhost/endpoint",
    curlPlaceholder: "curl -X POST http://example.localhost/endpoint \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"key\": \"value\"}'",
  },

  // Requests panel
  requests: {
    title: "Requests",
    noRequestsYet: "No saved requests yet.\nClick  +  in the tab bar.",
    noRequestsOpen: "No requests open",
    noRequestsOpenHint: "Click a request in the tree, or press + to create a new one.",
    newRequest: "New Request",
    editRequest: "Edit Request",
    searchPlaceholder: "Search requests…",
    requestCount: "{count} request{s}",
    importTitle: "Import requests from Postman Collection JSON",
    exportTitle: "Export requests as Postman Collection JSON",
    imported: "Imported {n} request{s} · {f} folder{fs}",
    exported: "Exported {n} request{s}",
    importFailed: "Import failed",
    exportFailed: "Export failed",
    requestNamePlaceholder: "Request name (optional)",
    urlPlaceholder: "https://example.localhost/endpoint",
    importFromCurl: "Import from cURL",
    curlPlaceholder: "curl -X POST https://example.localhost/endpoint \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"key\": \"value\"}'",
    createMock: "Create Mock",
    createMockTitle: "Create a mock pre-filled with this request + response",
    hitSendPrompt: "Hit Send to see the response",
    helpText: "Save and replay HTTP requests. Use the URL tree or folder view in the sidebar to browse saved requests. Paste a cURL command to auto-fill fields. After sending, use 'Create Mock' to instantly stub the response. Use {{VAR}} tokens in URL, headers, and body with an active environment.",
    newTab: "New request",
    closeTab: "Close",
    drafts: "Drafts",
    collectionFallback: "Collection",
  },

  // Capture panel
  capture: {
    title: "Capture",
    helpText: "Capture live HTTP requests passing through the proxy. Click 'Mock' to create a mock pre-filled with the captured request/response. Click 'Open' to replay in the Requests panel. Pause to stop the live feed.",
    exportTitle: "Export captured requests as Postman collection",
    exported: "Exported {n} request{s}",
    exportFailed: "Export failed",
    // Toolbar
    start: "Start",
    pause: "Pause",
    clear: "Clear",
    mockAll: "Mock All",
    saveAll: "Save All",
    searchPlaceholder: "URL, method, host…",
    selectedCount: "{count} selected",
    // Empty states
    emptyTitle: "No captured requests",
    emptyPausedHint: "Click Start to begin capturing HTTP traffic.",
    emptyLiveHint: "HTTP traffic will appear here as requests pass through the app.",
    emptyNoMatch: "No entries match your filter.",
    // Columns
    colName: "Name",
    colMethod: "Method",
    colStatus: "Status",
    colType: "Type",
    colFulfilledBy: "Fulfilled By",
    colSize: "Size",
    colTime: "Time",
    selectAll: "Select all",
    // Type tabs
    typeAll: "All",
    typeXhr: "Fetch/XHR",
    typeDoc: "Doc",
    typeCss: "CSS",
    typeJs: "JS",
    typeFont: "Font",
    typeImg: "Img",
    typeMedia: "Media",
    typeOther: "Other",
    // Fulfilled-by labels
    fulfilledExternal: "External",
    fulfilledProxy: "Proxy",
    fulfilledMock: "Mock",
    fulfilledError: "Error",
    // Detail tabs
    tabHeaders: "Headers",
    tabPayload: "Payload",
    tabResponse: "Response",
    tabTiming: "Timing",
    detailRequestHeaders: "Request Headers",
    detailResponseHeaders: "Response Headers",
    timingStarted: "Started",
    timingDuration: "Duration",
    timingStatus: "Status",
    timingFulfilledBy: "Fulfilled By",
    timingSize: "Size",
    emptyBody: "empty body",
    noHeaders: "No headers",
    closeDetail: "Close details",
    // Context menu — single row
    ctxMock: "Mock this request",
    ctxOpen: "Open in Requests",
    ctxSave: "Save to requests",
    ctxBlock: "Block request",
    ctxUnblock: "Unblock request",
    ctxShare: "Share (as JSON file)",
    ctxDelete: "Delete",
    // Context menu — multiple rows
    ctxMockMany: "Mock these requests",
    ctxSaveMany: "Save these to requests",
    ctxBlockMany: "Block these requests",
    ctxUnblockMany: "Unblock these requests",
    ctxShareMany: "Share these (as JSON file)",
    ctxDeleteMany: "Delete selected",
    subtitle: "Captured requests — persisted across sessions · last {count} kept",
    blockedPrefix: "Blocked —",
    replayResult: "Replay Result",
    sendingRequest: "Sending request…",
    responseHeaderCount: "{count} response headers",
    requestFailed: "Request failed",
    requestBodyPlaceholder: "Request body (optional)",
    sendToSeeResponse: "Send the request to see the response",
    headerCount: "{count} headers",
    createMockResponseTitle: "Create mock pre-filled with this response",
    createMockRequestTitle: "Create mock from request (send first to auto-fill response)",
    mockThisResponse: "Mock this response",
  },

  // Mappings panel
  mappings: {
    title: "Localhost Mappings",
    subtitle: "Map *.localhost domains to local services",
    noMappingsYet: "No mappings yet",
    noMappingsYetHint: "Map a .localhost subdomain to a local service port.",
    noMatchingMappings: "No matching mappings",
    noMatchingMappingsHint: "Try a different search term.",
    addMapping: "+ Add Mapping",
    editMapping: "Edit Mapping",
    addMappingTitle: "Add Mapping",
    searchPlaceholder: "Domain, target…",
    columnDomain: "Domain",
    columnTarget: "Target",
    columnLabel: "Label",
    columnOn: "On",
    helpText: "Create subdomain mappings like example.localhost → 127.0.0.1:3000. Browsers resolve *.localhost to 127.0.0.1 automatically (RFC 6761) — no hosts file edits needed. The server must be running on port 80 for bare hostnames to work.",
    subdomainLabel: "Subdomain",
    subdomainPlaceholder: "example or client.example",
    localHostSuffix: ".localhost",
    willCreate: "Will create:",
    targetLabel: "Target (ip:port)",
    targetPlaceholder: "127.0.0.1:3000",
    labelLabel: "Label (optional)",
    labelPlaceholder: "My App",
    subdomainRequired: "Subdomain is required",
    subdomainInvalid: "Each label must contain only letters, numbers, hyphens (no leading/trailing hyphens)",
    subdomainDuplicate: "{domain} is already mapped",
    targetInvalid: "Enter a valid host:port (e.g. 127.0.0.1:3000)",
    exportTitle: "Export mappings to JSON",
    importTitle: "Import mappings from JSON",
    exported: "Exported {n} mapping{s}",
    exportFailed: "Export failed",
    imported: "Imported {n} mapping{s}",
    importFailed: "Import failed",
    publish: "Publish",
    revert: "Revert",
    viewHistory: "View history",
  },

  // Settings panel
  settings: {
    title: "Settings",
    subtitle: "Server configuration and data management",
    helpText: "Configure the proxy server port, tray behavior, and export/import your mappings and rules. Mocks and requests are managed separately in their own panels.",
    serverPort: "Server Port",
    serverPortDesc: "Port the server listens on. Use {hint} in your browser.",
    minimizeToTray: "Minimize to Tray on Close",
    minimizeToTrayDesc: "Keep the app running in the system tray instead of quitting when the window is closed.",
    restartServer: "Restart Server",
    restartServerDesc: "Stop and restart the background proxy server on the configured port.",
    exportConfig: "Export All Data",
    exportConfigDesc: "Save all workspaces and their data to a JSON file.",
    importConfig: "Import All Data",
    importConfigDesc: "Restore all workspaces from a previously exported JSON file. Replaces everything.",
    exportBtn: "Export…",
    importBtn: "Import…",
    configImported: "Config imported.",
    port80Hint: "Port 80:",
    port80Example: "example.localhost",
    port80Desc: "— browsers resolve {domain} to 127.0.0.1 automatically (RFC 6761).",
    otherPortHint: "Other port:",
    otherPortDesc: "Use {domain} in the browser. No proxy setup needed.",
    proxyHint: "System/browser proxy:",
    proxyDesc: "Optionally set {addr} as your HTTP proxy. Proxy rules then apply to all HTTP traffic. HTTPS is a transparent TCP tunnel — not inspected.",
    sectionServer: "Server",
    sectionTls: "TLS Interception",
    sectionConfig: "Configuration",
    sectionAbout: "About",
    tlsEnabled: "Intercept HTTPS",
    tlsEnabledDesc: "When enabled, HTTPS requests are decrypted so mocks and proxy rules can match them. Requires a trusted CA certificate configured below.",
    tlsCaCert: "CA Certificate",
    tlsCaCertDesc: "PEM-encoded CA certificate used to sign per-host certificates.",
    tlsCaKey: "CA Private Key",
    tlsCaKeyDesc: "Private key for the CA certificate.",
    tlsImport: "Import…",
    tlsRemove: "Remove",
    tlsNotConfigured: "Not configured",
    tlsInstallHint: "Install the CA certificate in your browser or OS trust store to avoid HTTPS warnings.",
    tlsGenerate: "Generate with mkcert",
    tlsGenerating: "Generating…",
    tlsInstallCA: "Install in System",
    tlsInstalling: "Installing…",
    tlsInstallSuccess: "Installed",
    tlsInstallFailed: "Install failed",
    tlsExportCert: "Export Cert…",
    tlsManualInstall: "Manual install required — run in a terminal:",
    tlsGenerateHint: "Generate a new local CA cert using mkcert (10-year validity, stored in app data). Then install it so browsers trust your local HTTPS.",
    darkMode: "Theme",
    darkModeDesc: "Choose a colour theme for the application",
    version: "Version",
    author: "Author",
    authorName: "Harshal Kudale",
    github: "GitHub",
    githubUrl: "https://github.com/HarshalKudale",
    githubDisplay: "github.com/HarshalKudale",
    license: "License",
    licenseName: "MIT License",
    appDesc: "Local development proxy & mock server",
    webhookServerPort: "Webhook Server Port",
    webhookServerPortDesc: "Port for the dedicated webhook HTTP server (default 9101). Start/stop from the Webhooks panel.",
    currentlyLabel: "Currently:",
    companionPort: "Companion Extension Port",
    companionPortDesc: "WebSocket port for the companion browser extension (default 9271). The extension connects here to send captured requests.",
    themeGroupDark: "Dark",
    themeGroupLight: "Light",
    httpsIntercepted: "HTTPS traffic is intercepted and decrypted — mocks and proxy rules apply.",
    httpsTunnel: "HTTPS is a transparent TCP tunnel — not inspected.",
    sectionAppearance: "Appearance",
    sidebarPanels: "Sidebar Panels",
    sidebarPanelsDesc: "Choose which panels are visible in the sidebar",
    sidebarPanelsShown: "{visibleCount} of {n} shown",
    alwaysVisible: "Always visible",
    starOnGitHub: "Star on GitHub",
    supportProject: "Support Project",
  },

  // Services panel
  services: {
    title: "Services",
    helpText: "Discovers processes listening on localhost ports. Click 'Map →' next to any service to quickly create a localhost mapping for it. Hit Refresh to re-scan for new services.",
    subtitle: "Processes currently listening on localhost ports",
    searchPlaceholder: "Port, process…",
    refresh: "Refresh",
    colProcess: "Process",
    colAddress: "Address",
    colPort: "Port",
    colStatus: "Status",
    colMap: "Map",
    mapped: "Mapped",
    unmapped: "Unmapped",
    mapAction: "Map",
    pid: "PID {pid}",
    noMatching: "No matching services",
    noServices: "No services found",
    noMatchingHint: "Try a different search term.",
    noServicesHint: "No processes are listening on localhost ports.",
  },

  // Proxy rules panel
  proxyRules: {
    title: "Proxy Rules",
    helpText: "Proxy rules apply when Local Panel is configured as your system or browser HTTP proxy. Each rule matches a URL pattern and forwards matching requests to a mapped local service or external host. Rules are evaluated top-to-bottom — first match wins. Use request/response scripts to manipulate traffic.",
    exportTitle: "Export proxy rules to JSON",
    importTitle: "Import proxy rules from JSON",
    exported: "Exported {n} rule{s}",
    exportFailed: "Export failed",
    imported: "Imported {n} rule{s}",
    importFailed: "Import failed",
    newRule: "New Rule",
    newTab: "New rule",
    closeTab: "Close tab",
    drafts: "Drafts",
    noRulesOpen: "No rules open",
    searchPlaceholder: "Search rules…",
    collapseSidebar: "Collapse sidebar",
    expandSidebar: "Expand sidebar",
    saveRule: "Save Rule",
    ruleNamePlaceholder: "Rule name (optional)",
    targetMapping: "Mapped Service",
    targetExternal: "External Host",
    requestScript: "Request Script",
    responseScript: "Response Script",
    regexToggle: "Regex",
    exactToggle: "Exact",
    requestScriptPlaceholder: "// Runs before request is forwarded\n// lp.request.headers — mutable object\n// lp.request.body    — mutable string",
    responseScriptPlaceholder: "// Runs before response is returned\n// lp.response.headers — mutable object\n// lp.response.body    — mutable string",
    ruleLabel: "Proxy Rule",
    matchUrl: "Match URL",
    forwardTo: "Forward To",
    switchToExact: "Switch to exact match",
    switchToRegex: "Switch to regex match",
    regexHelp: "Tested as a JavaScript regex against the full request URL.",
    exactHelp: "Exact string match against the full request URL.",
    selectMapping: "— select a mapping —",
    noMappingsDefined: "No mappings defined. Add one in the Mappings panel.",
    updateRule: "Update Rule",
    patternRequired: "Pattern is required",
    invalidRegexPattern: "Invalid regex pattern",
    selectTargetMapping: "Select a target mapping",
    enterHostPort: "Enter a host:port or domain",
    deleteConfirm: "Delete this rule? This cannot be undone.",
    noRulesOpenHintPrefix: "Click a rule in the tree, or press",
    noRulesOpenHintSuffix: "to create a new one.",
    copySuffix: " (copy)",
    rulesCountTitle: "{count} rules",
  },

  // Environments panel
  environments: {
    title: "Environments",
    helpText: "Environments hold named variable sets. Switch the active environment from the title bar dropdown. Use {{VAR_NAME}} syntax anywhere in request/mock URLs, headers, body, or response body — values are substituted at send/match time. Variables not found in the active env are left as-is.",
    exportTitle: "Export environments to JSON",
    importTitle: "Import environments from JSON",
    exported: "Exported {n} environment{s}",
    exportFailed: "Export failed",
    imported: "Imported {n} environment{s}",
    importFailed: "Import failed",
    environmentName: "Environment name",
    alwaysActive: "Always Active",
    setActive: "Set Active",
    active: "Active",
    viewHistory: "View history",
    noVariables: "No variables — click Add Variable below",
    addVariable: "Add Variable",
    newEnvironment: "New Environment",
    noEnvironments: "No environments yet",
    noEnvironmentsDesc: "Create environments to manage variable sets for different stages.",
    useVarPrefix: "Use",
    useVarSuffix: "syntax anywhere in your requests and mocks.",
  },

  // Sockets panel
  sockets: {
    helpText: "Open persistent WebSocket connections to local or remote servers. Save connections with URLs and headers for quick access. OutputStream shows sent messages; InputStream shows received messages. Use {{VAR}} tokens in URL and message body with an active environment. Max 5 live connections at any time.",
    newSocket: "New Socket",
    editSocket: "Edit Socket",
    namePlaceholder: "Socket name (optional)",
    connect: "Connect",
    disconnect: "Disconnect",
    maxConnectionsTitle: "Max {n} active connections",
    connectionsActive: "{n} connections active — disconnect another tab before connecting here.",
    outputStream: "OutputStream",
    noMessagesSent: "No messages sent yet",
    typeMessage: "Type a message…",
    connectToSend: "Connect to send messages",
    live: "Live",
    waiting: "Waiting",
    clear: "Clear",
    waitingForMessages: "Waiting for messages…",
    connectToReceive: "Connect to receive messages",
    saveSocket: "Save Socket",
    updateSocket: "Update Socket",
    searchPlaceholder: "Search sockets…",
    newTab: "New socket",
    noSocketsOpen: "No sockets open",
    noSocketsHintPrefix: "Click a socket in the tree, or press",
    noSocketsHintSuffix: "to create one.",
  },

  // Editor sections
  editor: {
    request: "Request",
    response: "Response",
    headers: "Headers",
    body: "Body",
    preScript: "Pre Script",
    postScript: "Post Script",
    inputstream: "InputStream",
    outputstream: "OutputStream",
    readOnly: "read-only",
    status: "Status",
    replayRequest: "Replay Request",
    back: "Back",
    scriptPlaceholder: "// JavaScript — runs before the request is sent\n// Available: lp.request.url, lp.request.headers, lp.request.body\n//            lp.environment.get/set/unset\n//            await lp.sendRequest(requestId)  → { status, headers, body }",
    postScriptPlaceholder: "// JavaScript — runs after the response is received\n// Available: lp.response.status, lp.response.headers, lp.response.body, lp.response.json()\n//            lp.environment.get/set/unset\n//            await lp.sendRequest(requestId)  → { status, headers, body }",
    scriptError: "Script error",
    modeJson: "JSON",
    modeText: "Text",
    modeHtml: "HTML",
    modeXml: "XML",
    modeForm: "Form",
    modeMultipart: "Multipart",
    modeBinary: "Binary",
    modeImage: "Image",
    modeNone: "None",
    noBody: "No body",
    noFormFields: "No form fields",
    noMultipartFields: "No multipart fields",
    noFileSelected: "No file selected",
    browse: "Browse",
    addField: "Add field",
    colType: "Type",
    typeTextToggle: "T",
    typeFileToggle: "F",
    placeholderKey: "key",
    placeholderValue: "value",
    placeholderFieldName: "field name",
    fileTooLarge: "File too large ({size}). Max: 1 MB",
    failedToOpenFile: "Failed to open file",
    activeEnv: "Active env: {name}",
    variablesHeader: "{name} variables",
    emptyValue: "empty",
    insertRandomToken: "Insert random value token",
    randomizerTokens: "Randomizer tokens",
    insert: "Insert",
    ctxClose: "Close",
    ctxCloseOthers: "Close Others",
    ctxCloseAll: "Close All",
    ctxDuplicate: "Duplicate",
    params: "Params",
    tests: "Tests",
    script: "Script",
    results: "Results",
    console: "Console",
    pass: "PASS",
    fail: "FAIL",
    noTestResults: "No test results yet. Write tests and send the request.",
    noQueryParams: "No query params — add a row or type ?key=value in the URL",
    noRequestBodyCaptured: "No request body captured",
    requestBodyOptional: "Request body (optional)",
    delay: "Delay",
    ms: "ms",
    msPerChunk: "ms/chunk",
    streamNone: "No Stream",
    streamSse: "SSE",
    streamChunked: "Chunked",
    responseDelayTitle: "Response delay in milliseconds",
    streamingModeTitle: "Streaming mode",
    chunkDelayTitle: "Chunk delay in ms",
    responseStatusTitle: "Response status code",
    status200: "200  OK",
    status201: "201  Created",
    status204: "204  No Content",
    status301: "301  Moved Permanently",
    status302: "302  Found",
    status304: "304  Not Modified",
    status400: "400  Bad Request",
    status401: "401  Unauthorized",
    status403: "403  Forbidden",
    status404: "404  Not Found",
    status405: "405  Method Not Allowed",
    status409: "409  Conflict",
    status422: "422  Unprocessable Entity",
    status429: "429  Too Many Requests",
    status500: "500  Internal Server Error",
    status502: "502  Bad Gateway",
    status503: "503  Service Unavailable",
    matchUrlAsRegex: "Match URL as regular expression",
    invalidRegex: "Invalid regex",
    requestFailed: "Request failed",
    saveFailed: "Save failed",
    preScriptError: "Pre-script: {error}",
    postScriptError: "Post-script: {error}",
    saveRequest: "Save Request",
    updateRequest: "Update Request",
    updateMock: "Update Mock",
  },

  // Workspace panel
  workspace: {
    title: "Workspace",
    subtitle: "Configure workspace settings and remote sync",
    helpText: "Manage workspace name and connect to a remote Git repository for syncing across machines. Connecting pushes local data to an empty remote, or clones an existing remote into an empty workspace.",
    sectionDetails: "Details",
    sectionSync: "Remote Sync",
    sectionData: "Data",
    sectionDanger: "Danger Zone",
    workspaceName: "Workspace Name",
    workspaceCreated: "Created",
    remoteUrl: "Remote URL",
    remoteUrlDesc: "Git repository URL. Cannot be changed once connected.",
    remoteUrlPlaceholder: "https://github.com/you/workspace-data.git",
    branch: "Branch",
    branchPlaceholder: "main",
    autoSync: "Auto-sync",
    autoSyncDesc: "Automatically push after changes and pull every 30 seconds.",
    connectBtn: "Connect",
    connectingBtn: "Connecting…",
    disconnectBtn: "Disconnect",
    pushBtn: "Push",
    pullBtn: "Pull",
    pushingBtn: "Pushing…",
    pullingBtn: "Pulling…",
    lastPushed: "Last pushed",
    lastPulled: "Last pulled",
    never: "never",
    statusIdle: "Synced",
    statusPushing: "Pushing…",
    statusPulling: "Pulling…",
    statusCloning: "Connecting…",
    statusError: "Error",
    exportBtn: "Export Workspace…",
    exportDesc: "Save this workspace's data to a JSON file.",
    importBtn: "Import Into Workspace…",
    importDesc: "Replace this workspace's data from a previously exported JSON file.",
    deleteBtn: "Delete Workspace",
    deleteDesc: "Permanently delete this workspace and all its data.",
    deleteConfirm: "This will permanently delete \"{name}\" and all its data. Are you sure?",
    deleteConfirmBtn: "Delete",
    connectWarningNonEmpty: "Your local data will be pushed to the remote. The remote must be empty.",
    connectWarningEmpty: "The remote repository will be cloned into this workspace. Continue?",
    confirmConnect: "Connect",
    cancelConnect: "Cancel",
    syncError: "Sync error",
    disconnectWarning: "Disconnect from remote? Local data is preserved.",
    disconnectConfirm: "Disconnect",
    imported: "Workspace imported",
    exported: "Workspace exported",
    importFailed: "Import failed",
    exportFailed: "Export failed",
  },

  // Applications panel
  applications: {
    title: "Applications",
    subtitle: "Run configurations for your workspace",
    helpText: "Configure and run application processes. Supports Node.js, Python, Java, .NET, Go, Docker, Maven, Gradle, Spring Boot, and shell scripts.",
    addApplication: "Add Application",
    updateApplication: "Update Application",
    noTitle: "No applications configured",
    noDesc: "Add run configurations to start, stop, and debug your applications from here.",
    labelName: "Name",
    labelType: "Type",
    labelWorkingDirectory: "Working Directory",
    labelCommand: "Command",
    labelScriptPath: "Script Path",
    labelScriptName: "Script Name",
    labelPackageManager: "Package Manager",
    labelModule: "Module (-m)",
    labelMainClass: "Main Class",
    labelJarPath: "JAR Path (optional)",
    labelClasspath: "Classpath",
    labelImage: "Image",
    labelPorts: "Ports (comma-separated)",
    labelComposeFile: "Compose File",
    labelArguments: "Arguments",
    labelPreRunCommand: "Pre-Run Command",
    labelDebugPort: "Debug Port",
    noOutputYet: "No output yet",
    debugListeningOn: "Debugger listening on port",
    statusRunning: "Running",
    statusDebugging: "Debugging",
    statusStarting: "Starting\u2026",
    statusStopping: "Stopping\u2026",
    statusError: "Error",
    statusExited: "Exited",
    statusIdle: "Idle",
    actionRun: "Run",
    actionDebug: "Debug",
    actionStop: "Stop",
    actionRestart: "Restart",
    logsTitle: "Output",
    logsClear: "Clear",
    logsScrollBottom: "Scroll to bottom",
    configNamePlaceholder: "Configuration name…",
    sectionRunConfigType: "Run Configuration Type",
    sectionConfiguration: "Configuration",
    sectionBeforeLaunch: "Before Launch",
    browse: "Browse",
    browseFile: "Browse for file",
    browseFolder: "Browse for folder",
    dialogSelectFile: "Select File",
    dialogSelectFolder: "Select Folder",
    dialogSelectScriptFile: "Select Script File",
    dialogSelectEntryPoint: "Select Entry Point",
    dialogSelectPythonScript: "Select Python Script",
    dialogSelectJarFile: "Select JAR File",
    dialogSelectPom: "Select pom.xml",
    dialogSelectSettings: "Select settings.xml",
    dialogSelectGradleProject: "Select Gradle Project",
    dialogSelectProjectFile: "Select Project File",
    dialogSelectDockerfile: "Select Dockerfile",
    dialogSelectBuildContext: "Select Build Context",
    dialogSelectComposeFile: "Select Compose File",
    dialogSelectProjectDirectory: "Select Project Directory",
    labelScriptFile: "Script File",
    labelInterpreter: "Interpreter",
    labelNodeFlags: "Node Flags",
    labelInspectorPort: "Inspector Port",
    labelModuleName: "Module Name",
    labelLaunchMode: "Launch Mode",
    labelJarFile: "JAR File",
    labelClasspath: "Classpath",
    labelVmOptions: "VM Options",
    labelSystemProperties: "System Properties",
    labelBuildTool: "Build Tool",
    labelActiveProfiles: "Active Profiles",
    labelVmArguments: "VM Arguments",
    labelProgramArguments: "Program Arguments",
    labelBeforeLaunchGoal: "Before Launch Goal",
    labelMavenExecutable: "Maven Executable",
    labelPomFile: "POM File",
    labelGoals: "Goals",
    labelProfiles: "Profiles (-P)",
    labelJvmArguments: "JVM Arguments",
    labelPropertiesD: "Properties (-D)",
    labelSettingsFile: "Settings File (-s)",
    labelGradleExecutable: "Gradle Executable",
    labelProjectDirectory: "Project Directory",
    labelTasks: "Tasks",
    labelExtraArguments: "Extra Arguments",
    labelPropertiesP: "Properties (-P)",
    labelProjectFile: "Project File (.csproj / .fsproj)",
    labelConfiguration: "Configuration",
    labelTargetFramework: "Target Framework",
    labelLaunchProfile: "Launch Profile",
    labelPackagePath: "Package Path",
    labelBuildFlags: "Build Flags",
    labelRunMode: "Run Mode",
    labelDockerfile: "Dockerfile",
    labelBuildContext: "Build Context",
    labelPortMappings: "Port Mappings",
    labelVolumeMounts: "Volume Mounts",
    labelEnvironmentVariables: "Environment Variables",
    labelNetwork: "Network",
    labelEntrypointOverride: "Entrypoint Override",
    labelExtraDockerRunArguments: "Extra docker run Arguments",
    labelServices: "Services",
    labelProfile: "Profile",
    labelDebugPortOverride: "Debug Port Override",
    hintRequired: "required",
    hintOptional: "optional",
    hintInterpreter: "optional — default: system shell",
    hintForDebugMode: "for debug mode",
    hintScriptName: "from package.json scripts",
    hintModuleName: "e.g. uvicorn.main",
    hintMainClass: "required — e.g. com.example.Application",
    hintClasspath: "colon/semicolon separated or . for CWD",
    hintVmOptions: "-Xmx, -Xms, GC flags, etc.",
    hintSystemProperties: "-Dkey=value, one per line",
    hintCommaSeparated: "comma-separated",
    hintMainClassAutoDetected: "optional — auto-detected",
    hintBeforeLaunchGoal: "optional — compile step",
    hintPomFile: "optional — uses pom.xml in working dir",
    hintGoals: "space or comma separated",
    hintPropertiesD: "one -Dkey=value per line",
    hintPropertiesP: "one -Pkey=value per line",
    hintPackagePath: "e.g. ./cmd/server or ./...",
    hintLaunchProfile: "from launchSettings.json — optional",
    hintHostContainer: "host:container, one per line",
    hintEnvVars: "KEY=VALUE, one per line",
    hintServices: "optional — space-separated",
    hintPreRunCommand: "runs in working directory before start",
    hintDebugPortOverride: "default: auto",
    filterShellScripts: "Shell Scripts",
    filterBatchFiles: "Batch Files",
    filterPowerShell: "PowerShell",
    filterVbscript: "VBScript",
    filterAllFiles: "All Files",
    filterJavaScript: "JavaScript",
    filterPythonFiles: "Python Files",
    filterJarFiles: "JAR Files",
    filterPomFiles: "POM Files",
    filterXmlFiles: "XML Files",
    filterProjectFiles: "Project Files",
    filterDockerfile: "Dockerfile",
    filterComposeFiles: "Compose Files",
    checkboxEnableAssertions: "Enable assertions (-ea)",
    checkboxSkipTestsMaven: "Skip tests (-DskipTests)",
    checkboxSkipTestsGradle: "Skip tests (-x test)",
    checkboxNoBuild: "No Build (--no-build)",
    checkboxRaceDetector: "Race Detector (-race)",
    checkboxBuildImages: "Build images before starting (--build)",
    buildToolMaven: "Maven",
    buildToolGradle: "Gradle",
    runModePullImage: "Pull Image",
    runModeBuildRun: "Build & Run",
    runtimeNode: "Node.js",
    runtimePython: "Python",
    runtimeJava: "Java",
    runtimeSpringBoot: "Spring Boot",
    runtimeMaven: "Maven",
    runtimeGradle: "Gradle",
    runtimeDotnet: ".NET",
    runtimeGo: "Go",
    runtimeDocker: "Docker",
    runtimeDockerCompose: "Docker Compose",
    runtimeShellScript: "Shell Script",
    runtimeBatchFile: "Batch File",
    runtimePowershell: "PowerShell",
    runtimeVbscript: "VBScript",
    applicationStatus: "Application Status",
    statRunning: "RUNNING",
    statStopped: "STOPPED",
    statDebugActive: "DEBUG ACTIVE",
    statErrors: "ERRORS",
    menuEditConfig: "Edit Config",
    infoRuntime: "Runtime",
    infoPort: "Port",
    infoPid: "PID",
    infoUptime: "Uptime",
    infoDebugPort: "Debug Port",
    infoUrl: "URL",
    openMappedUrl: "Open mapped URL",
    openInBrowser: "Open in browser",
    addMappingForUrl: "Add mapping for this URL",
    badgeErrored: "errored",
    badgeExited: "exited",
    logOutput: "Log Output — {name}",
    closeLogPanel: "Close log panel",
    startToSeeOutput: "Start the application to see log output",
    confirmDelete: "Delete this application? This cannot be undone.",
  },

  // Import/export
  io: {
    cancelled: "Cancelled",
    importFailed: "Import failed",
    exportFailed: "Export failed",
  },

  // GraphQL tabs & panels
  graphql: {
    requestTitle: "GRAPHQL REQUEST",
    mockTitle: "GRAPHQL MOCK",
    requestNamePlaceholder: "Request name…",
    mockNamePlaceholder: "Mock name…",
    methodPost: "POST",
    endpoint: "ENDPOINT",
    sending: "Sending",
    regex: "Regex",
    tabQuery: "Query",
    tabVariables: "Variables",
    tabHeaders: "Headers",
    tabPreScript: "Pre-Script",
    tabPostScript: "Post-Script",
    tabSchema: "Schema",
    tabMatch: "Match",
    tabResponseHeaders: "Response Headers",
    operationType: "Operation Type",
    opAny: "Any",
    opQuery: "Query",
    opMutation: "Mutation",
    opSubscription: "Subscription",
    operationName: "Operation Name",
    operationNamePlaceholder: "Match operation name (leave empty to match all)",
    responseStatus: "Response Status",
    responseDelay: "Response Delay (ms)",
    response: "Response",
    responseBody: "Response Body",
    responsePlaceholder: "Send a request to see the response…",
    update: "Update",
    schema: "Schema",
    back: "Back",
    introspect: "+ Introspect",
    introspecting: "Introspecting…",
    fetchSchema: "Fetch Schema",
    introspectionFailed: "Introspection failed",
    networkError: "Network error",
    selectSchema: "Select schema…",
    filterOperations: "Filter operations…",
    noSchemasLoaded: "No schemas loaded. Click \"Introspect\" to fetch a schema from a GraphQL endpoint.",
    noOperationsInSchema: "No operations found in schema.",
    insertQueryTemplate: "Insert {name} query template",
    deleteMockConfirm: "Delete this mock? This cannot be undone.",
    deleteRequestConfirm: "Delete this request? This cannot be undone.",
    copySuffix: "{name} (copy)",
    untitled: "Untitled",
    newMockTab: "New GraphQL Mock",
    newRequestTab: "New GraphQL Request",
    newMockTabTitle: "New GraphQL mock",
    newRequestTabTitle: "New GraphQL request",
    closeTab: "Close tab",
    drafts: "Drafts",
    searchMocks: "Search mocks…",
    searchRequests: "Search requests…",
    collapseSidebar: "Collapse sidebar",
    expandSidebar: "Expand sidebar",
    noMocksOpen: "No GraphQL mocks open",
    noMocksOpenHintBefore: "Mock GraphQL operations by matching query names and types. Click",
    noMocksOpenHintAfter: "to create your first mock.",
    noRequestsOpen: "No GraphQL requests open",
    noRequestsOpenHint: "Send GraphQL queries and mutations. Import a schema or use server introspection to get started.",
    mockCount: "{count} mocks",
    requestCount: "{count} requests",
  },

  // gRPC tabs & panels
  grpc: {
    requestTitle: "gRPC Request",
    mockTitle: "gRPC Mock",
    requestNamePlaceholder: "Request name…",
    mockNamePlaceholder: "Mock name…",
    sending: "Sending…",
    streamUnary: "Unary",
    streamServer: "Server Stream",
    streamClient: "Client Stream",
    streamBidi: "Bidi Stream",
    streamBidirectional: "Bidirectional",
    streamServerStreaming: "Server Streaming",
    streamClientStreaming: "Client Streaming",
    type: "Type:",
    useReflection: "Use Reflection",
    enabled: "Enabled",
    tabMessage: "Message",
    tabMetadata: "Metadata",
    tabPreScript: "Pre-Script",
    tabPostScript: "Post-Script",
    tabProto: "Proto",
    tabResponse: "Response",
    tabTrailingMetadata: "Trailing Metadata",
    tabResponseBody: "Response Body",
    tabResponseMetadata: "Response Metadata",
    tabSettings: "Settings",
    noMetadata: "No metadata. Add key-value pairs for gRPC metadata.",
    noResponseMetadata: "No response metadata.",
    responseDelay: "Response Delay (ms)",
    errorCode: "Error Code (0 = no error)",
    errorMessage: "Error Message",
    errorMessagePlaceholder: "Optional error message",
    status: "Status:",
    noResponseYet: "No response yet. Send a request to see results.",
    responseNumber: "Response #{n}",
    noTrailingMetadata: "No trailing metadata received.",
    update: "Update",
    unknownError: "Unknown error",
    sendFailed: "Send failed",
    reflectionFailed: "Reflection failed",
    connectionFailed: "Connection failed",
    proto: "Proto",
    back: "Back",
    import: "+ Import",
    importProtoFile: "Import .proto File",
    or: "OR",
    reflecting: "Reflecting…",
    serverReflection: "Server Reflection",
    selectProtoFile: "Select proto file…",
    filterMethods: "Filter methods…",
    noProtoFiles: "No proto files loaded. Click \"Import\" to add a .proto file or use server reflection.",
    selectMethod: "Select {service}/{method}",
    deleteMockConfirm: "Delete this mock? This cannot be undone.",
    deleteRequestConfirm: "Delete this request? This cannot be undone.",
    copySuffix: "{name} (copy)",
    newMockTab: "New gRPC Mock",
    newRequestTab: "New gRPC Request",
    newMockTabTitle: "New gRPC mock",
    newRequestTabTitle: "New gRPC request",
    closeTab: "Close tab",
    mockLabel: "gRPC Mock",
    requestLabel: "gRPC Request",
    unnamed: "Unnamed",
    drafts: "Drafts",
    searchMocks: "Search gRPC mocks…",
    searchRequests: "Search gRPC requests…",
    collapseSidebar: "Collapse sidebar",
    expandSidebar: "Expand sidebar",
    stopMockServer: "Stop gRPC mock server",
    startMockServer: "Start gRPC mock server",
    mockServerRunning: "Mock server :{port}",
    mockServerStopped: "Mock server stopped",
    noMocksOpen: "No gRPC mocks open",
    noMocksOpenHint: "Run a local gRPC mock server. Import proto definitions to register service methods and configure responses.",
    noRequestsOpen: "No gRPC requests open",
    noRequestsOpenHint: "Make gRPC calls. Import a .proto file or use server reflection to discover available methods.",
    mockCount: "{count} mocks",
    requestCount: "{count} requests",
  },

  // SOAP tabs & panels
  soap: {
    requestTitle: "SOAP Request",
    mockTitle: "SOAP Mock",
    requestNamePlaceholder: "Untitled Request",
    mockNamePlaceholder: "Untitled Mock",
    methodPost: "POST",
    sending: "Sending",
    soapAction: "SOAPAction:",
    endpointPattern: "Endpoint Pattern:",
    soapActionMatch: "SOAPAction Match:",
    responseStatus: "Response Status:",
    delay: "Delay (ms):",
    regex: "Regex",
    tabBody: "Body",
    tabHeaders: "Headers",
    tabPreScript: "Pre-Script",
    tabPostScript: "Post-Script",
    tabWsdl: "WSDL",
    tabResponseBody: "Response Body",
    tabResponseHeaders: "Response Headers",
    noResponseYet: "No response yet",
    update: "Update",
    requestFailed: "Request failed",
    wsdl: "WSDL",
    back: "Back",
    fetchWsdl: "+ Fetch WSDL",
    fetching: "Fetching…",
    fetchAndImport: "Fetch & Import",
    fetchWsdlFailed: "Failed to fetch WSDL",
    networkError: "Network error",
    selectWsdl: "Select WSDL…",
    filterOperations: "Filter operations…",
    noWsdlsImported: "No WSDLs imported. Click \"Fetch WSDL\" to import a WSDL from a URL.",
    noOperationsInWsdl: "No operations found in WSDL.",
    insertEnvelope: "Insert {name} SOAP envelope",
    deleteMockConfirm: "Delete this mock? This cannot be undone.",
    deleteRequestConfirm: "Delete this request? This cannot be undone.",
    copySuffix: "{name} (copy)",
    newMockTab: "New SOAP Mock",
    newRequestTab: "New SOAP Request",
    newMockTabTitle: "New SOAP mock",
    newRequestTabTitle: "New SOAP request",
    closeTab: "Close tab",
    mockLabel: "SOAP Mock",
    requestLabel: "SOAP Request",
    drafts: "Drafts",
    searchMocks: "Search SOAP mocks…",
    searchRequests: "Search SOAP requests…",
    collapseSidebar: "Collapse sidebar",
    expandSidebar: "Expand sidebar",
    noMocksOpen: "No SOAP mocks open",
    noMocksOpenHintBefore: "Mock SOAP services by matching SOAPAction headers and operation names. Click",
    noMocksOpenHintAfter: "to create your first mock.",
    noRequestsOpen: "No SOAP requests open",
    noRequestsOpenHint: "Send SOAP requests. Import a WSDL to discover available operations and auto-generate envelopes.",
    mockCount: "{count} mocks",
    requestCount: "{count} requests",
  },

  // Collection runner
  runner: {
    requestCount: "{count} request{s}",
    requestsHeader: "Requests",
    requests: "requests",
    tests: "tests",
    failed: "failed",
    delay: "Delay",
    ms: "ms",
    run: "Run",
    runAgain: "Run Again",
    running: "Running...",
    allPassed: "All passed",
    someFailed: "Some failed",
    exportTitle: "Export report as HTML or JSON",
    dragToReorder: "- drag to reorder",
    noRequests: "No requests in this folder.",
    untitled: "Untitled",
    pressRunPrefix: "Press",
    pressRunSuffix: "to execute all requests in this collection.",
    error: "Error",
    preScriptLabel: "Pre-script:",
    postScriptLabel: "Post-script:",
    console: "Console",
  },

  // Webhooks panel
  webhooks: {
    title: "Webhooks",
    newWebhook: "New Webhook",
    webhook: "Webhook",
    namePlaceholder: "Webhook name (optional)",
    searchPlaceholder: "Search webhooks…",
    newTab: "New webhook",
    drafts: "Drafts",
    received: "Received",
    emptyBody: "(empty body)",
    empty: "(empty)",
    waitingForPost: "Waiting for POST requests…",
    activateToReceive: "Activate this webhook to receive payloads.",
    selectPayload: "Select a payload to view its body",
    openToReceive: "Open a webhook to start receiving POST requests",
    saveWebhook: "Save Webhook",
    updateWebhook: "Update Webhook",
    statusActive: "Active",
    statusAtLimit: "At limit",
    statusInactive: "Inactive",
    maxActive: "Max {n} webhooks active — close another tab to activate this one.",
    stopServer: "Stop webhook server",
    startServer: "Start webhook server",
    serverLabel: "Webhook server",
    serverStopped: "Webhook server stopped",
  },

  // Health bar panel
  healthBar: {
    title: "Health Bar",
    service: "service",
    services: "services",
    notChecked: "Not checked",
    checking: "Checking…",
    error: "Error",
    unknown: "Unknown",
    viewLastResponse: "View last response",
    lastChecked: "Last checked",
    autoRefresh: "Auto refresh",
    refreshService: "Refresh this service",
    removeService: "Remove service",
    refreshAll: "Refresh All",
    addService: "Add Service",
    editService: "Edit Service",
    serviceName: "Service Name",
    healthCheckUrl: "Health Check URL",
    supportsEnvVars: "Supports environment variables:",
    nameRequired: "Name is required",
    urlRequired: "Health check URL is required",
    urlInvalid: "Enter a valid URL (e.g. http://localhost:3000/health)",
    update: "Update",
    publish: "Publish",
    publishing: "Publishing…",
    synced: "Health Bar is synced",
    loadingServices: "Loading services…",
    noServices: "No services added",
    noServicesDesc: "Add a service to start monitoring its health check endpoint.",
  },

  // Logs panel
  logs: {
    title: "Logs",
    subtitle: "HTTP traffic through the app — via proxy or RFC 6761",
    searchPlaceholder: "URL, method, host…",
    resume: "Resume",
    pause: "Pause",
    clear: "Clear",
    noEntries: "No log entries",
    emptyHint: "HTTP traffic will appear here as requests pass through the app.",
    noMatch: "No entries match your search.",
    colTime: "Time",
    colMethod: "Mth",
    colStatus: "St",
    colUrl: "URL",
    colVia: "Via",
    colDur: "Dur",
    replay: "Replay",
    replayTitle: "Replay this request",
    mock: "Mock",
    mockTitle: "Create mock from this request",
    entries: "entries",
    shown: "shown",
    paused: "paused",
    footerNote: "newest first · last {max} kept · auto-cleared when full",
  },

  // Audit log panel
  auditLog: {
    title: "Audit Log",
    subtitle: "Every configuration change in this workspace —",
    entries: "entries",
    loading: "Loading…",
    noEntries: "No audit entries found.",
    loadingDiff: "Loading diff…",
    noSnapshot: "No snapshot data available.",
    entityDeleted: "Entity was deleted.",
    beforeStateStored: "Before state stored in git history.",
    entityCreated: "Entity was created — no prior state.",
    noFieldChanges: "No field changes detected.",
    allEntities: "All entities",
    entityMock: "Mock",
    entityMapping: "Mapping",
    entityRule: "Proxy Rule",
    entityEnvironment: "Environment",
    entityRequest: "Request",
    entityWebSocket: "WebSocket",
    entityFolder: "Folder",
    entityWorkspace: "Workspace",
    allActions: "All actions",
    actionCreate: "Create",
    actionUpdate: "Update",
    actionDelete: "Delete",
  },

  // Folder tree (sidebar)
  folderTree: {
    renameFolder: "Rename Folder",
    moveToFolder: "Move to Folder",
    slashRoot: "/ root",
    root: "root",
    expandAll: "Expand All",
    collapseAll: "Collapse All",
    newSubfolder: "New Subfolder",
    newTab: "New Tab",
    commitPushFolder: "Commit & Push Folder",
    enableAllInFolder: "Enable All in Folder",
    disableAllInFolder: "Disable All in Folder",
    deleteFolder: "Delete Folder",
    runCollection: "Run Collection",
    unblock: "Unblock",
    open: "Open",
    commitDelete: "Commit Delete",
    commitPush: "Commit & Push",
    restore: "Restore",
    discardChanges: "Discard Changes",
    disable: "Disable",
    enable: "Enable",
    duplicate: "Duplicate",
    history: "History",
    block: "Block",
    delete: "Delete",
    move: "Move",
    expand: "Expand",
    collapse: "Collapse",
    nItems: "{n} item{s}",
    nFolders: "{n} folder{s}",
    nSelected: "{n} selected",
    and: " and ",
    deleteConfirmTracked: "Delete {what}? The item will be removed locally. You can still restore it or commit the deletion later from the context menu.",
    deleteConfirmUntracked: "Delete {what}? This item has never been committed and will be permanently removed.",
    pendingDeletion: "Pending Deletion",
    pendingDeletionBody: "has been deleted locally but not yet committed. You can restore it or commit the deletion to git.",
  },

  // Sidebar (app shell)
  sidebar: {
    searchPlaceholderDefault: "Search…",
    searchPanels: "Search panels…",
    noPanelsFound: "No panels found",
    switchWorkspace: "Switch workspace",
    workspace: "Workspace",
    workspaceOptions: "Workspace options",
    workspaceSettings: "Workspace Settings",
    auditLog: "Audit Log",
    createWorkspace: "Create Workspace",
    workspaces: "Workspaces",
    renameWorkspace: "Rename workspace",
    deleteWorkspace: "Delete workspace",
    deleteWorkspacePrefix: "Delete",
    deleteWorkspaceSuffix: "? All data in this workspace will be permanently removed.",
    discardDraft: "Discard draft",
  },

  // Entity history sidebar
  history: {
    title: "{kind} History",
    kindRequest: "Request",
    kindMock: "Mock",
    kindSocket: "Socket",
    kindEnvironment: "Environment",
    kindMapping: "Mapping",
    kindRule: "Rule",
    kindEntity: "Entity",
    closeHistory: "Close history",
    commit: "commit{s}",
    loading: "Loading…",
    noHistory: "No history found for this file.",
    localActor: "local",
    loadingDiff: "Loading diff…",
    noSnapshot: "No snapshot available.",
    deletedPrior: "Deleted — prior state in git history.",
    createdNoPrior: "Created — no prior state.",
    noFieldChanges: "No field changes detected.",
    hideUnchanged: "Hide {n} unchanged",
    showUnchanged: "Show {n} unchanged",
  },

  // Import/export modal
  importExport: {
    kindWorkspace: "Workspace",
    kindRequests: "Requests",
    kindMocks: "Mocks",
    kindEnvironments: "Environments",
    kindMappings: "Mappings",
    kindProxyRules: "Proxy Rules",
    kindWebsockets: "WebSockets",
    kindWebhooks: "Webhooks",
    descWorkspace: "Export/import entire workspace with all entities",
    descRequests: "Saved HTTP requests and folders",
    descMocks: "Mock response rules and folders",
    descEnvironments: "Environment variable sets",
    descMappings: "Domain-to-target proxy mappings",
    descProxyRules: "URL pattern proxy rules",
    descWebsockets: "WebSocket connection definitions",
    descWebhooks: "Webhook endpoint definitions",
    exportData: "Export Data",
    importData: "Import Data",
    exporting: "Exporting…",
    importing: "Importing…",
    exportComplete: "Export complete.",
    exportFailed: "Export failed.",
    importFailed: "Import failed.",
    couldNotReadFile: "Could not read file.",
    importedItems: "Imported {n} item{s}",
    skippedSuffix: ", skipped {n}",
    whatToWorkWith: "What would you like to work with?",
    chooseExportFormatFor: "Choose export format for",
    chooseImportFormatFor: "Choose import format for",
    noFormatsAvailable: "No formats available.",
    back: "Back",
    exportEllipsis: "Export…",
    chooseFile: "Choose File…",
    collisionSummary: "{count} of {total} items have matching IDs in this workspace.",
    howConflictsHandled: "How should conflicts be handled?",
    import: "Import",
    collisionKeepLabel: "Keep existing",
    collisionOverrideLabel: "Override with imported",
    collisionNewLabel: "Import as new copies",
    collisionKeepDesc: "Conflicting items are skipped; only new items are imported.",
    collisionOverrideDesc: "Imported items replace the existing ones with the same ID.",
    collisionNewDesc: "All imported items get new IDs — no conflicts.",
  },

  // Global footer (sync status)
  footer: {
    syncing: "syncing",
    changesWaitingToPublish: "changes waiting to be published",
    changesNotYetCommitted: "changes not yet committed",
    publishing: "Publishing…",
    publish: "Publish",
    sync: "sync",
    local: "local",
    upToDate: "up to date",
    commitLocalChangesTitle: "Commit local changes (no remote configured)",
  },

  // Panel registry (sections & help)
  panels: {
    sectionRest: "REST",
    sectionGraphql: "GraphQL",
    sectionSoap: "SOAP",
    sectionGrpc: "gRPC",
    sectionWebsocket: "WebSocket",
    sectionWebhooks: "Webhooks",
    sectionRunConfigs: "Run Configs",
    sectionHealthBar: "Health Bar",
    sectionWorkspace: "Workspace",
    sectionAuditLog: "Audit Log",
    sectionMock: "Mock",
    sectionRequest: "Request",
    sectionApplications: "Applications",
    graphqlMockHelp: "Create GraphQL mock operations. Match incoming queries and mutations by operation name and return configured responses.",
    soapMockHelp: "Create SOAP mock services. Match incoming requests by SOAPAction header and return configured XML responses.",
    grpcMockHelp: "Create gRPC mock services. Run a local gRPC server that returns configured responses for matched methods.",
    graphqlRequestHelp: "Send GraphQL queries and mutations. Import schemas via introspection or SDL files for query generation.",
    soapRequestHelp: "Send SOAP requests. Import WSDL files to discover operations and auto-generate request envelopes.",
    grpcRequestHelp: "Make gRPC calls. Import .proto files or use server reflection to discover services and methods.",
    webhooksHelp: "Create and manage webhooks. Open a webhook in a tab to activate it and receive POST requests on the webhook server.",
    healthbarHelp: "Monitor health check endpoints for your services. Responses are fetched live from the main process.",
    auditHelp: "A complete history of every configuration change in this workspace.",
  },

  // Binary viewer
  binary: {
    preview: "Preview",
    hex: "Hex",
    base64: "Base64",
    copyBase64: "Copy base64",
    upload: "Upload",
    dropFile: "Drop a file here or click Upload",
    noBinaryData: "No binary data",
    fileTooLarge: "File too large ({size}). Max: 1 MB",
  },
} as const;
